# Generated by Django 4.1.3 on 2022-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_wav_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='wav_files'),
        ),
    ]
