# Generated by Django 4.1.3 on 2022-11-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_wav_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='sample_bool',
        ),
    ]
